from __future__ import annotations

from pathlib import Path
import csv
import math
import pandas as pd
import numpy as np

from .materials import load_materials
from .solver import simulate
from .solar import plane_of_array

ROOT = Path(__file__).resolve().parents[1]
EXPORT_DIR = ROOT / "exports" / "ansys"


def _safe_name(value: str) -> str:
    return "".join(ch if ch.isalnum() or ch in "_-" else "_" for ch in value)


def _write_boundary_files(result, weather, boundary: Path, apdl_table: Path, material_absorptance: float = 0.65):
    times = result["series"]["time"]
    outside = result["series"]["t_air_out_c"]
    inside = result["series"]["t_air_in_c"]
    # The Level A wall panel is a conduction + convection cross-check.
    # Its sol-air input is the outside-air temperature plus a fixed solar term
    # only when an irradiance series is available. This is kept explicit rather
    # than inventing a radiation model inside the ANSYS handoff.
    h_out = 9.0
    h_in = 1.0 / 0.13
    result_index = pd.DatetimeIndex(times)
    w = weather.frame.reindex(result_index).interpolate("time").ffill().bfill()
    poa = plane_of_array(90.0, 180.0, result_index,
                         np.maximum(w["ghi_wm2"].to_numpy(dtype=float), 0.0),
                         np.maximum(w["dhi_wm2"].to_numpy(dtype=float), 0.0),
                         np.maximum(w["dni_wm2"].to_numpy(dtype=float), 0.0),
                         float(weather.meta.get("lat", 34.1526)),
                         float(weather.meta.get("lon", 77.5771)),
                         float(weather.meta.get("ground_reflectance", 0.2)) if weather.meta.get("ground_reflectance") is not None else 0.2)
    with boundary.open("w", newline="", encoding="utf-8") as fh:
        w = csv.writer(fh)
        w.writerow(["time", "outside_air_c", "sol_air_c", "h_out_w_m2k", "indoor_air_c", "h_in_w_m2k"])
        for t, o, i, g in zip(times, outside, inside, poa):
            sol_air = float(o) + material_absorptance * max(float(g), 0.0) / h_out
            w.writerow([t, o, sol_air, h_out, i, h_in])
def export_ansys_case(design, weather, materials_path, glazing_path):
    EXPORT_DIR.mkdir(parents=True, exist_ok=True)
    result = simulate(design, weather, materials_path, glazing_path, dt_minutes=10, run="free")

    boundary = EXPORT_DIR / "boundary_conditions.csv"
    apdl_table = EXPORT_DIR / "boundary_conditions_table.txt"
    python_wall = EXPORT_DIR / "python_wall_results.csv"
    mats_out = EXPORT_DIR / "materials.csv"
    macro = EXPORT_DIR / "wall_panel.mac"

    mats = load_materials(materials_path)
    outer_name = design["constructions"]["wall"][-1]["material"]
    outer_abs = float(mats[outer_name].absorptance)
    _write_boundary_files(result, weather, boundary, apdl_table, outer_abs)

    # Keep a directly comparable Python wall temperature series for the team.
    wall_surface = result["series"].get("surface_temp_in_c", {}).get("wall_main")
    if wall_surface is None:
        raise ValueError("Solver result does not contain wall_main inner surface temperatures")
    with python_wall.open("w", newline="", encoding="utf-8") as fh:
        w = csv.writer(fh)
        w.writerow(["timestamp", "inner_surface_c"])
        for t, temp in zip(result["series"]["time"], wall_surface):
            w.writerow([t, temp])

    with mats_out.open("w", newline="", encoding="utf-8") as fh:
        w = csv.writer(fh)
        w.writerow(["material", "lambda_w_mk", "rho_kg_m3", "c_j_kgk", "source"])
        names = []
        for layer in design["constructions"]["wall"]:
            name = layer["material"]
            if name not in names:
                names.append(name)
        for name in names:
            m = mats[name]
            w.writerow([m.name, m.lambda_w_mk, m.rho_kg_m3, m.c_j_kgk, m.source])

    # Generate a self-contained macro with exact material values and layer stack.
    result_times = pd.to_datetime(result["series"]["time"], utc=True)
    first_time = result_times[0]
    last_time = result_times[-1]
    end_time_s = (last_time - first_time).total_seconds()
    h_in = 1.0 / 0.13
    h_out = 9.0
    initial_temp_c = float(result["series"]["t_air_in_c"][0])
    layer_defs = list(design["constructions"]["wall"])
    total_m = sum(float(layer["mm"]) for layer in layer_defs) / 1000.0
    nrows = len(result["series"]["time"])
    unique_materials = []
    for layer in layer_defs:
        if layer["material"] not in unique_materials:
            unique_materials.append(layer["material"])

    lines = [
        "/COM, VAJRA Level A wall panel thermal cross-check",
        "/COM, Generated by VAJRA for a team-side ANSYS Level A wall-panel cross-check.",
        "/COM, Review the installed ANSYS release and confirm SOLID278 is available.",
        "/COM, All geometry and thermal properties use SI units.",
        "/CLEAR,START",
        "/PREP7",
        "ET,1,SOLID278",
    ]
    for idx, name in enumerate(unique_materials, start=1):
        m = mats[name]
        lines += [
            f"! Material {idx}: {name}",
            f"MP,KXX,{idx},{m.lambda_w_mk:.12g}",
            f"MP,DENS,{idx},{m.rho_kg_m3:.12g}",
            f"MP,C,{idx},{m.c_j_kgk:.12g}",
        ]
    lines += [
        "! One square metre wall panel. X is outside-to-inside thickness; Y and Z are 1 m.",
    ]
    x = 0.0
    for i, layer in enumerate(layer_defs, start=1):
        thick = float(layer["mm"]) / 1000.0
        x1 = x + thick
        lines.append(f"BLOCK,{x:.8g},{x1:.8g},0,1,0,1")
        lines.append(f"VSEL,S,VOLU,,{i}")
        lines.append(f"VATT,{unique_materials.index(layer['material'])+1},,1")
        x = x1
    lines += [
        "VSEL,ALL",
        *(["VGLUE,ALL"] if len(layer_defs) > 1 else []),
        "ESIZE,0.025",
        "VMESH,ALL",
        "ALLSEL,ALL",
        "",
        "! Read time, outside air, inside air, h_out and h_in from tab-delimited file.",
        f"*DIM,TAMB,TABLE,{nrows},1,1,TIME",
        f"*DIM,TIND,TABLE,{nrows},1,1,TIME",
        f"*TREAD,TAMB,boundary_conditions_table,txt,,1",
        f"*TREAD,TIND,boundary_conditions_table_inside,txt,,1",
        "",
        "! The exporter writes two helper files with the scalar tables.",
        "NSEL,S,LOC,X,0",
        f"SF,ALL,CONV,{h_out:.8g},%TAMB%",
        f"NSEL,S,LOC,X,{total_m:.8g}",
        f"SF,ALL,CONV,{h_in:.8g},%TIND%",
        f"NSEL,S,LOC,X,{total_m:.8g}",
        "NSEL,R,LOC,Y,0.5",
        "NSEL,R,LOC,Z,0.5",
        "*GET,INNER_NODE,NODE,0,NUM,MIN",
        "ALLSEL,ALL",
        f"IC,ALL,TEMP,{float(initial_temp_c):.8g}",
        "FINISH",
        "/SOLU",
        "ANTYPE,TRANS",
        "TIMINT,ON",
        "AUTOTS,ON",
        "KBC,1",
        "DELTIM,600,60,1800",
        f"TIME,{max(end_time_s, 600.0):.8g}",
        "OUTRES,ALL,ALL",
        "SOLVE",
        "FINISH",
        "",
        "/POST26",
        "NUMVAR,20",
        "NSOL,2,INNER_NODE,TEMP,,INNER_T",
        "STORE,MERGE",
        "*GET,NSETS,VARI,,NSETS",
        "*DIM,VTIME,ARRAY,NSETS",
        "*DIM,VTEMP,ARRAY,NSETS",
        "VGET,VTIME(1),1",
        "VGET,VTEMP(1),2",
        "/COM, Export time and inner surface temperature.",
        "*CFOPEN,ansys_wall_results,csv",
        "*VWRITE,'time_s','inner_surface_c'",
        "(A8,',',A18)",
        "*DO,II,1,NSETS",
        "*VWRITE,VTIME(II),VTEMP(II)",
        "(F16.3,',',F16.6)",
        "*ENDDO",
        "*CFCLOSE",
        "FINISH",
    ]
    # Replace the two-table approximation with a single helper for each dependent variable.
    helper_amb = EXPORT_DIR / "boundary_conditions_table.txt"
    helper_in = EXPORT_DIR / "boundary_conditions_table_inside.txt"
    first = result_times[0]
    with helper_amb.open("w", encoding="utf-8") as fh: 
        fh.write("time_s\ttemp_c\n")
        for t, val in zip(result["series"]["time"], result["series"]["t_air_out_c"]):
            stamp = pd.Timestamp(t) if not hasattr(t, "to_pydatetime") else t
            if not hasattr(stamp, "tzinfo"):
                stamp = pd.Timestamp(stamp)
            stamp_s = (pd.Timestamp(stamp) - pd.Timestamp(first)).total_seconds()
            fh.write(f"{stamp_s:.3f}\t{float(val):.6f}\n")
    with helper_in.open("w", encoding="utf-8") as fh:
        fh.write("time_s\ttemp_c\n")
        for t, val in zip(result_times, result["series"]["t_air_in_c"]):
            stamp_s = (pd.Timestamp(t) - pd.Timestamp(first)).total_seconds()
            fh.write(f"{stamp_s:.3f}\t{float(val):.6f}\n")
    macro.write_text("\n".join(lines) + "\n", encoding="utf-8")

    return [boundary, mats_out, macro, apdl_table, helper_in, python_wall]
